import type { InputHTMLAttributes, ReactNode, SelectHTMLAttributes } from "react";

type BaseProps = { label: string; icon: ReactNode; error?: string };
export function FormInput({ label, icon, error, className = "", ...props }: BaseProps & InputHTMLAttributes<HTMLInputElement>) {
  return <label className={`block ${className}`}><span className="mb-2 block text-[13px] font-semibold text-[#343548]">{label}</span><span className={`group flex h-[52px] items-center gap-3 rounded-xl border bg-white px-4 transition focus-within:border-[#765cdf] focus-within:ring-4 focus-within:ring-[#765cdf]/10 ${error ? "border-red-400" : "border-[#dedce7]"}`}><span className="h-5 w-5 shrink-0 text-[#9999a9] transition group-focus-within:text-[#7056d9]">{icon}</span><input {...props} className="min-w-0 flex-1 border-0 bg-transparent text-[15px] text-[#222337] outline-none placeholder:text-[#aaaab7]" aria-invalid={Boolean(error)}/></span>{error && <span className="mt-1.5 block text-xs text-red-600">{error}</span>}</label>;
}
export function FormSelect({ label, icon, error, children, ...props }: BaseProps & SelectHTMLAttributes<HTMLSelectElement>) {
  return <label className="block"><span className="mb-2 block text-[13px] font-semibold text-[#343548]">{label}</span><span className={`group flex h-[52px] items-center gap-3 rounded-xl border bg-white px-4 transition focus-within:border-[#765cdf] focus-within:ring-4 focus-within:ring-[#765cdf]/10 ${error ? "border-red-400" : "border-[#dedce7]"}`}><span className="h-5 w-5 shrink-0 text-[#9999a9] transition group-focus-within:text-[#7056d9]">{icon}</span><select {...props} className="min-w-0 flex-1 appearance-none border-0 bg-transparent text-[15px] text-[#222337] outline-none invalid:text-[#aaaab7]" aria-invalid={Boolean(error)}>{children}</select><svg className="h-4 w-4 text-[#9999a9]" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="m6 8 4 4 4-4" strokeLinecap="round" strokeLinejoin="round"/></svg></span>{error && <span className="mt-1.5 block text-xs text-red-600">{error}</span>}</label>;
}
